spring:
  application:
    name: BRMProject2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Chetan@123
    url: jdbc:mysql://localhost:3306/springboot
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
